### ISSUE TITLE
Cannot GET / installing in sub directory

### ISSUE THREAD

**Issue by ddoonn** [vue-bulma/vue-admin#144]
I'm installing this under my root as so:
```
    --package.json
    --node_modules
    --vue-admin
       -build
       -client
       -docs
       -etc
```

I have update the directories for webpack.base.conf.js and webpack.dev.conf.js and get ```'webpack: bundle is now VALID.'``` after running ```npm run dev``` but I still get ```cannot GET /``` when the browser launches. Can anyone point me in the right direction where things are going wrong?

**Comment by luventa** [comment]
Clone or download vue-admin
```
 --vue-admin
    -build     
    -client
    -docs
    -etc
```
execute `npm install` inside folder `../vue-admin`
folder `node_modules` will be generated automatically inside `../vue-admin`
now execute `npm run dev` inside `../vue-admin`
Your web browser will shows up and wait for 'webpack: bundle is now VALID.'

**Comment by ddoonn** [comment]
cheers @luventa, this works. However I would like it to keep all my node_modules in the root of the project. 
I was wondering more specifically which package isn't configured correctly that produces the ```cannot GET /``` I understand the problem is either in one of the ```webpack.config.js ``` files or ```router/index.js``` could you perhaps point me in the right direction?

**Comment by luventa** [comment]
I don't think it's caused by configuration.
If webpack dev server is not launched, you cannot get the `cannot Get / ` exception.
So dev server must be launched, but router may not be built and installed correctly (or you won't get the exception because router will set location to `Home`). 
This situation is caused by `node_modules` and that's why this exception occurs I guess.
